### ISSUE TITLE
solidjs verses svelte

### ISSUE THREAD

**Issue by gedw99** [atdiar/particleui#7] opened 2022-07-13 12:34 UTC
I like the code but think the approach solidjs takes to be much better with golang.
SolidJs does not follow svelte on purpose. I think Solidjs people got it right as they say.
https://www.solidjs.com/ has 2 very short video's that show how it does reactivity. Its very clear from the video...

For golang this is easy and natural way to do reactivity and state.

Have a look and see what your think.

**Comment by atdiar** [comment] 2022-07-13 16:33
Hi,

Can you tell me more about the difference between solidjs and sveltejs wrt reactive state management?

I'm curious although reactivity is already implemented in particleui and is slightly different from svelte or solidjs or mobx(yet similar in some ways).

**Comment by atdiar** [comment] 2022-08-19 14:23
Does not seem that there is anything to do here?


Currently, ParticleUI implements **Reactive Element Properties**. This is much easier to use than anything else in my opinion as programming languages do not have reactive _variables_ by default.

For instance, a signal (as implemented in numerous other frameworks) is a way to create an atomic reactive instance.
The issue is that it is often only observable inside the components it is defined in. It does not allow inter-component variable observations, or at least, it is not straigthforward.

The approach we are taking here is that each UI element has properties that are mutable. An Element can then decide to wacth another element's property and react when it changes. This is a simple implementation of the observer's pattern.

So UI Elements are reactive. But variables still aren't. (this is different from svelte here)
Go variables are still not reactive. It would be difficult to retrofit reactivity on them anyway and wouldn't even help much to tame state management complexity.

Code example:
```go
// Let's create two div elements
SomeDiv:= doc.NewDiv("somediv")
OtherDiv:= doc.NewDiv("otherdiv")

// This reads as: SomeDiv watches the "text" property that resides in the "ui" namespace/category of OtherDiv
// It registers a new Mutation handler that gets triggered when that property changes.
SomeDiv.AsElement().Watch("ui","text",OtherDiv,ui.NewMutationHandler(func(evt MutationEvent)bool{
        SomeDiv.AsElement()).Set("ui","text", evt.NewValue())
        return false
    })
)

OtherDiv.AsElement().Set("ui","text", String("just some text))

// SomeDiv will see that "just some text" was set for the "text" property in the "ui" category/namespace and will 
// set the same value for its own ("ui","text")  property.

```
Perhaps it looks a little boilerplaty but it should be really easy to understand once the method signature is internalized.
And code completion alleviates the issue if there is one (I'm used ot it myself now).
The semantics are really kept as simple and straightforward as possible.

It still allows for fine-grained reactivity. There is no notion of rendering or dom-diffing in ParticleUI. It is not needed.

I will close this issue now. If there is some additional insight that you (@gedw99) want to provide, feel free to comment here or open a new one.

Thanks again, state management is really an important topic indeed!

**Closed by atdiar** 2022-08-19 14:23 UTC
